version: '2.2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - ${PORT}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./custom.conf:/etc/nginx/conf.d/custom.conf
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: proxy_nw

